### ISSUE TITLE
Flutter plugin crashes on android with latest update

### ISSUE THREAD

**Issue by aghanti7** [thegrizzlylabs/geniusscan-sdk-demo#25]
We are using Flutter stable v1.17.0 and genius scan plugin v3.0.17. The scanner opens up and then crashes soon as you tap on the capture (camera) button.

This wasn't happening before the flutter upgrade.

Here is the error:
```
05-11 17:33:35.870   954  3265 V WindowManager: mCurrentFocus: Window{75f763c u0 com.teakshed.omrx/com.thegrizzlylabs.geniusscan.sdk.ui.ScanActivity} newFocus Window{357ef96 u0 com.teakshed.omrx/com.thegrizzlylabs.geniusscan.sdk.ui.ScanActivity}
05-11 17:33:35.870   954  3265 V WindowManager: Changing focus from Window{75f763c u0 com.teakshed.omrx/com.thegrizzlylabs.geniusscan.sdk.ui.ScanActivity} to Window{357ef96 u0 com.teakshed.omrx/com.thegrizzlylabs.geniusscan.sdk.ui.ScanActivity} Callers=com.android.server.wm.WindowManagerService.addWindow:2087 com.android.server.wm.Session.addToDisplay:205 android.view.IWindowSession$Stub.onTransact:124 com.android.server.wm.Session.onTransact:166 
05-11 17:33:35.872   954  3265 D WindowManager: Input focus has changed to Window{357ef96 u0 com.teakshed.omrx/com.thegrizzlylabs.geniusscan.sdk.ui.ScanActivity}
05-11 17:33:35.873   954   984 I WindowManager: Focus moving from Window{75f763c u0 com.teakshed.omrx/com.thegrizzlylabs.geniusscan.sdk.ui.ScanActivity} to Window{357ef96 u0 com.teakshed.omrx/com.thegrizzlylabs.geniusscan.sdk.ui.ScanActivity}
05-11 17:33:35.875   823   823 D AndroidRuntime: Shutting down VM
05-11 17:33:35.877   823   823 E AndroidRuntime: FATAL EXCEPTION: main
05-11 17:33:35.877   823   823 E AndroidRuntime: Process: com.teakshed.omrx, PID: 823
05-11 17:33:35.877   823   823 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lbolts/Task;
05-11 17:33:35.877   823   823 E AndroidRuntime: 	at com.thegrizzlylabs.geniusscan.sdk.ui.CameraFragment.rotatePageAndFinish(Unknown Source:17)
05-11 17:33:35.877   823   823 E AndroidRuntime: 	at com.thegrizzlylabs.geniusscan.sdk.ui.CameraFragment.access$600(Unknown Source:0)
05-11 17:33:35.877   823   823 E AndroidRuntime: 	at com.thegrizzlylabs.geniusscan.sdk.ui.CameraFragment$d.onPictureTaken(Unknown Source:6)
05-11 17:33:35.877   823   823 E AndroidRuntime: 	at com.thegrizzlylabs.geniusscan.sdk.camera.ScanFragment$c.onPictureTaken(Unknown Source:20)
05-11 17:33:35.877   823   823 E AndroidRuntime: 	at com.thegrizzlylabs.geniusscan.sdk.camera.CameraManager$c.onPictureTaken(Unknown Source:33)
05-11 17:33:35.877   823   823 E AndroidRuntime: 	at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1369)
05-11 17:33:35.877   823   823 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-11 17:33:35.877   823   823 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:202)
05-11 17:33:35.877   823   823 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6962)
05-11 17:33:35.877   823   823 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-11 17:33:35.877   823   823 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:528)
05-11 17:33:35.877   823   823 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:888)
05-11 17:33:35.877   823   823 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "bolts.Task" on path: DexPathList[[zip file "/data/app/com.teakshed.omrx-C0-lTfUvgMxSbc5tF1O_Ng==/base.apk", zip file "/data/app/com.teakshed.omrx-C0-lTfUvgMxSbc5tF1O_Ng==/split_config.arm64_v8a.apk", zip file "/data/app/com.teakshed.omrx-C0-lTfUvgMxSbc5tF1O_Ng==/split_config.en.apk", zip file "/data/app/com.teakshed.omrx-C0-lTfUvgMxSbc5tF1O_Ng==/split_config.xhdpi.apk"],nativeLibraryDirectories=[/data/app/com.teakshed.omrx-C0-lTfUvgMxSbc5tF1O_Ng==/lib/arm64, /data/app/com.teakshed.omrx-C0-lTfUvgMxSbc5tF1O_Ng==/base.apk!/lib/arm64-v8a, /data/app/com.teakshed.omrx-C0-lTfUvgMxSbc5tF1O_Ng==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/com.teakshed.omrx-C0-lTfUvgMxSbc5tF1O_Ng==/split_config.en.apk!/lib/arm64-v8a, /data/app/com.teakshed.omrx-C0-lTfUvgMxSbc5tF1O_Ng==/split_config.xhdpi.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
05-11 17:33:35.877   823   823 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
05-11 17:33:35.877   823   823 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
05-11 17:33:35.877   823   823 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
05-11 17:33:35.877   823   823 E AndroidRuntime: 	... 12 more
05-11 17:33:35.877   823   823 E AndroidRuntime: 	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.teakshed.omrx-C0-lTfUvgMxSbc5tF1O_Ng==/split_config.arm64_v8a.apk
05-11 17:33:35.877   823   823 E AndroidRuntime: 		at dalvik.system.DexFile.openDexFileNative(Native Method)
05-11 17:33:35.877   823   823 E AndroidRuntime: 		at dalvik.system.DexFile.openDexFile(DexFile.java:353)
05-11 17:33:35.877   823   823 E AndroidRuntime: 		at dalvik.system.DexFile.<init>(DexFile.java:100)
05-11 17:33:35.877   823   823 E AndroidRuntime: 		at dalvik.system.DexFile.<init>(DexFile.java:74)
05-11 17:33:35.877   823   823 E AndroidRuntime: 		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
05-11 17:33:35.877   823   823 E AndroidRuntime: 		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
05-11 17:33:35.877   823   823 E AndroidRuntime: 		at dalvik.system.DexPathList.<init>(DexPathList.java:157)
05-11 17:33:35.877   823   823 E AndroidRuntime: 		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
05-11 17:33:35.877   823   823 E AndroidRuntime: 		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
05-11 17:33:35.877   823   823 E AndroidRuntime: 		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
05-11 17:33:35.877   823   823 E AndroidRuntime: 		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
05-11 17:33:35.877   823   823 E AndroidRuntime: 		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
05-11 17:33:35.877   823   823 E AndroidRuntime: 		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:35)
05-11 17:33:35.877   823   823 E AndroidRuntime: 		at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:743)
05-11 17:33:35.877   823   823 E AndroidRuntime: 		at android.app.LoadedApk.getClassLoader(LoadedApk.java:777)
05-11 17:33:35.877   823   823 E AndroidRuntime: 		at android.app.LoadedApk.getResources(LoadedApk.java:1017)
05-11 17:33:35.877   823   823 E AndroidRuntime: 		at android.app.ContextImpl.createAppContext(ContextImpl.java:2387)
05-11 17:33:35.877   823   823 E AndroidRuntime: 		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6032)
05-11 17:33:35.877   823   823 E AndroidRuntime: 		at android.app.ActivityThread.-wrap1(Unknown Source:0)
05-11 17:33:35.877   823   823 E AndroidRuntime: 		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
05-11 17:33:35.877   823   823 E AndroidRuntime: 		... 6 more
05-11 17:33:35.877   823   823 E AndroidRuntime: 	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.teakshed.omrx-C0-lTfUvgMxSbc5tF1O_Ng==/split_config.en.apk
05-11 17:33:35.877   823   823 E AndroidRuntime: 		at dalvik.system.DexFile.openDexFileNative(Native Method)
05-11 17:33:35.877   823   823 E AndroidRuntime: 		at dalvik.system.DexFile.openDexFile(DexFile.java:353)
05-11 17:33:35.877   823   823 E AndroidRuntime: 		at dalvik.system.DexFile.<init>(DexFile.java:100)
05-11 17:33:35.878   823   823 E AndroidRuntime: 		at dalvik.system.DexFile.<init>(DexFile.java:74)
05-11 17:33:35.878   823   823 E AndroidRuntime: 		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
05-11 17:33:35.878   823   823 E AndroidRuntime: 		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
05-11 17:33:35.878   823   823 E AndroidRuntime: 		at dalvik.system.DexPathList.<init>(DexPathList.java:157)
05-11 17:33:35.878   823   823 E AndroidRuntime: 		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
05-11 17:33:35.878   823   823 E AndroidRuntime: 		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
05-11 17:33:35.878   823   823 E AndroidRuntime: 		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
05-11 17:33:35.878   823   823 E AndroidRuntime: 		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
05-11 17:33:35.878   823   823 E AndroidRuntime: 		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
05-11 17:33:35.878   823   823 E AndroidRuntime: 		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:35)
05-11 17:33:35.878   823   823 E AndroidRuntime: 		at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:743)
05-11 17:33:35.878   823   823 E AndroidRuntime: 		at android.app.LoadedApk.getClassLoader(LoadedApk.java:777)
05-11 17:33:35.878   823   823 E AndroidRuntime: 		at android.app.LoadedApk.getResources(LoadedApk.java:1017)
05-11 17:33:35.878   823   823 E AndroidRuntime: 		at android.app.ContextImpl.createAppContext(ContextImpl.java:2387)
05-11 17:33:35.878   823   823 E AndroidRuntime: 		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6032)
05-11 17:33:35.878   823   823 E AndroidRuntime: 		at android.app.ActivityThread.-wrap1(Unknown Source:0)
05-11 17:33:35.878   823   823 E AndroidRuntime: 		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
05-11 17:33:35.878   823   823 E AndroidRuntime: 		... 6 more
05-11 17:33:35.878   823   823 E AndroidRuntime: 	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.teakshed.omrx-C0-lTfUvgMxSbc5tF1O_Ng==/split_config.xhdpi.apk
05-11 17:33:35.878   823   823 E AndroidRuntime: 		at dalvik.system.DexFile.openDexFileNative(Native Method)
05-11 17:33:35.878   823   823 E AndroidRuntime: 		at dalvik.system.DexFile.openDexFile(DexFile.java:353)
05-11 17:33:35.878   823   823 E AndroidRuntime: 		at dalvik.system.DexFile.<init>(DexFile.java:100)
05-11 17:33:35.878   823   823 E AndroidRuntime: 		at dalvik.system.DexFile.<init>(DexFile.java:74)
05-11 17:33:35.878   823   823 E AndroidRuntime: 		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
05-11 17:33:35.878   823   823 E AndroidRuntime: 		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
05-11 17:33:35.878   823   823 E AndroidRuntime: 		at dalvik.system.DexPathList.<init>(DexPathList.java:157)
05-11 17:33:35.878   823   823 E AndroidRuntime: 		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
05-11 17:33:35.878   823   823 E AndroidRuntime: 		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
05-11 17:33:35.878   823   823 E AndroidRuntime: 		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
05-11 17:33:35.878   823   823 E AndroidRuntime: 		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
05-11 17:33:35.878   823   823 E AndroidRuntime: 		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
05-11 17:33:35.878   823   823 E AndroidRuntime: 		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:35)
05-11 17:33:35.878   823   823 E AndroidRuntime: 		at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:743)
05-11 17:33:35.878   823   823 E AndroidRuntime: 		at android.app.LoadedApk.getClassLoader(LoadedApk.java:777)
05-11 17:33:35.878   823   823 E AndroidRuntime: 		at android.app.LoadedApk.getResources(LoadedApk.java:1017)
05-11 17:33:35.878   823   823 E AndroidRuntime: 		at android.app.ContextImpl.createAppContext(ContextImpl.java:2387)
05-11 17:33:35.878   823   823 E AndroidRuntime: 		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6032)
05-11 17:33:35.878   823   823 E AndroidRuntime: 		at android.app.ActivityThread.-wrap1(Unknown Source:0)
05-11 17:33:35.878   823   823 E AndroidRuntime: 		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
05-11 17:33:35.878   823   823 E AndroidRuntime: 		... 6 more
05-11 17:33:35.889   954  6319 W ActivityManager:   Force finishing activity com.teakshed.omrx/com.thegrizzlylabs.geniusscan.sdk.ui.ScanActivity
05-11 17:33:35.900   823   823 I Process : Sending signal. PID: 823 SIG: 9
```

Note: We have proguard rules and minify enabled. Here is our proguard file.
```
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-keep public class io.flutter.embedding.android.FlutterSplashView.$SavedState { *; }
-keepattributes InnerClasses
```

**Comment by aghanti7** [comment]
I noticed you have identified this issue here - https://github.com/thegrizzlylabs/geniusscan-sdk-demo/issues/17#issuecomment-558062062, but am unable to find out if we are running into a similar issue.

My guess is that we need to add something to proguard rules. Note that we cannot do away with proguard rules, because it brought down our app size by almost 40%.

Any help is appreciated!

**Comment by aghanti7** [comment]
Did a little more digging. Found out that bolts by FB/Parse is being used by geniusscan.sdk. Added the following to app/build.grade, and it worked!

```
dependencies {
...
   implementation 'com.parse.bolts:bolts-tasks:1.4.0'
   implementation 'com.parse.bolts:bolts-applinks:1.4.0'
...
}
```

Questions:

1. Is this the right fix?
2. Why was this working with 3.0.13 + Flutter 1.12 and suddenly broke with Flutter 1.17?

**Comment by guillaume-tgl** [comment]
Thanks for reporting this issue.

Yes, we started using Bolts Task in the latest version of the SDK and it seems like we didn't declare it correctly for cross-platform plugins. We'll make sure to fix this quickly. 
Sorry for the trouble.

In the meantime, adding `implementation 'com.parse.bolts:bolts-tasks:1.4.0'` to your Android dependencies should be enough.

**Comment by aghanti7** [comment]
Thanks @guillaume-tgl - will use this fix for now.

Request you to close this bug when the plugin gets updated, so that I can unroll the temp fix.

**Comment by guillaume-tgl** [comment]
Fixed in v3.0.18

**Comment by aghanti7** [comment]
After upgrading to latest, the scanner works, but I get the following exception in the logs:

```
E/WindowManager(24491): 	at androidx.fragment.app.Fragment.performResume(Fragment.java:2649)
E/WindowManager(24491): 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:922)
E/WindowManager(24491): 	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
E/WindowManager(24491): 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
E/WindowManager(24491): 	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
E/WindowManager(24491): 	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
E/WindowManager(24491): 	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
E/WindowManager(24491): 	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
E/WindowManager(24491): 	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
E/WindowManager(24491): 	at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
E/WindowManager(24491): 	at android.os.Handler.handleCallback(Handler.java:873)
E/WindowManager(24491): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/WindowManager(24491): 	at android.os.Looper.loop(Looper.java:193)
E/WindowManager(24491): 	at android.app.ActivityThread.main(ActivityThread.java:6898)
E/WindowManager(24491): 	at java.lang.reflect.Method.invoke(Native Method)
E/WindowManager(24491): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
E/WindowManager(24491): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by guillaume-tgl** [comment]
Could you open a new issue, paste the full stack trace and let us know how to reproduce this issue, if a crash happens...?
