### ISSUE TITLE
Build Flutter App with Android SDK Error

### ISSUE THREAD

**Issue by thomas4Bitcraft** [thegrizzlylabs/geniusscan-sdk-demo#27]
I have a problem calling the GeniusScan SDK from the Flutter App. I tried to break it down to the main cause and the App crashes when trying to initiate the Genius Scan SDK.

Here is the Stacktrace:
```
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/android.test.mock.jar", zip file
"/system/framework/android.test.runner.jar", zip file
"/data/app/com.wenatex.sales-Zw_vtvhnkiyPYZ9R1ms44A==/base.apk"],nativeLibraryDirectories=[/data/app/com.wenatex.sales-Zw_vtvhnkiyPYZ9R1ms44A==/lib/arm64,
/data/app/com.wenatex.sales-Zw_vtvhnkiyPYZ9R1ms44A==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libgs-sdk.so"
[        ] E/AndroidRuntime(13117):     at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
[        ] E/AndroidRuntime(13117):     at java.lang.System.loadLibrary(System.java:1669)
[        ] E/AndroidRuntime(13117):     at com.thegrizzlylabs.geniusscan.sdk.core.GeniusScanLibrary.<clinit>(GeniusScanLibrary.java:45)
[        ] E/AndroidRuntime(13117):     at com.thegrizzlylabs.geniusscan.sdk.core.GeniusScanLibrary.init(GeniusScanLibrary.java:54)
[        ] E/AndroidRuntime(13117):     at com.example.wenatex_android.TestActivity.initSDK(TestActivity.kt:26)
[        ] E/AndroidRuntime(13117):     at com.example.wenatex_android.TestActivity.onCreate(TestActivity.kt:21)
[        ] E/AndroidRuntime(13117):     at android.app.Activity.performCreate(Activity.java:7136)
[        ] E/AndroidRuntime(13117):     at android.app.Activity.performCreate(Activity.java:7127)
[        ] E/AndroidRuntime(13117):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
[        ] E/AndroidRuntime(13117):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2896)
[        ] E/AndroidRuntime(13117):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3051)
[        ] E/AndroidRuntime(13117):     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
[        ] E/AndroidRuntime(13117):     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
[        ] E/AndroidRuntime(13117):     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
[        ] E/AndroidRuntime(13117):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1811)
[        ] E/AndroidRuntime(13117):     at android.os.Handler.dispatchMessage(Handler.java:106)
[        ] E/AndroidRuntime(13117):     at android.os.Looper.loop(Looper.java:193)
[        ] E/AndroidRuntime(13117):     at android.app.ActivityThread.main(ActivityThread.java:6694)
[        ] E/AndroidRuntime(13117):     at java.lang.reflect.Method.invoke(Native Method)
[   +5 ms] E/AndroidRuntime(13117):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
[        ] E/AndroidRuntime(13117):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
[   +3 ms] I/Process (13117): Sending signal. PID: 13117 SIG: 9
[ +212 ms] Service protocol connection closed.
```

And this is the Code im currently using:
```
class TestActivity : Activity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_test2)

        initSDK()
    }

    private fun initSDK() {
        try { // Replace this key by your key
            GeniusScanLibrary.init(this, "<key>")
        } catch (e: LicenseException) {
            AlertDialog.Builder(this)
                    .setMessage("This version is not valid anymore. Please update to the latest version.")
                    .setPositiveButton(android.R.string.ok) { dialog, which -> finish() }
                    .show()
        } catch (e: Exception) {
            print(e)
        }
    }
}
```

project build.gradle:
```
buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()

        maven { url 'https://maven.fabric.io/public' }
        maven { url 'https://s3.amazonaws.com/tgl.maven' }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        // Add the google services classpath
        classpath 'com.google.gms:google-services:4.3.0'
        // Add fabric classpath
        classpath 'io.fabric.tools:gradle:1.26.1'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'androidx.core' &&
                    !details.requested.name.contains('androidx')) {
                details.useVersion "1.1.0"
            }
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

app build.gradle:
```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "<identifier>"
        minSdkVersion 19
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        manifestPlaceholders = [
                'appAuthRedirectScheme': 'com.wenatex.eventapp'
        ]
        multiDexEnabled true
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

repositories {
    maven { url 'https://s3.amazonaws.com/tgl.maven' }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
    implementation 'com.android.support:multidex:2.0.1'
    implementation 'com.google.firebase:firebase-firestore-ktx:21.4.1'
    // (Recommended) Add the Google Analytics dependency.
    implementation 'com.google.firebase:firebase-analytics:17.2.3'
    implementation 'com.thegrizzlylabs.geniusscan.sdk:gs-sdk:3.0.18'
    implementation 'com.thegrizzlylabs.geniusscan.sdk:gs-sdk-ocr:3.0.18'
    implementation 'com.parse.bolts:bolts-tasks:1.4.0'
    implementation 'com.parse.bolts:bolts-applinks:1.4.0'

    def supportLibraryVersion = '28.0.0'
    implementation "com.android.support:support-fragment:$supportLibraryVersion"
}

apply plugin: 'io.fabric'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'kotlin-android-extensions'
```

Does anybody know what is happening here?

**Comment by thomas4Bitcraft** [comment]
Ok the problem really only occurs on the `initSDK()` call - if i comment this out and start the MainActivity from the android demo-custom app it works.
