### ISSUE TITLE
[Android|beta] Simple Demo crashes when used with Pixel 4 XL API 30 (virtual device)

### ISSUE THREAD

**Issue by imanoupetit** [thegrizzlylabs/geniusscan-sdk-demo#37]
App crashes when user taps "Scan from camera" button.

# Requirements
- Set repo on branch "beta"
- Select Pixel 4 XL API 30 in AVD
- Build and run Android Simple Demo

# How to reproduce
- Launch Android Simple Demo project
- Tap "Scan from camera" button

# Logs
```
I/tflite: Initialized TensorFlow Lite runtime.
D/GeniusScanSDK: Getting camera
D/GeniusScanSDK: Number of cameras available : 2
I/GeniusScanSDK: Camera selected : 0
D/GeniusScanSDK: Got camera - cancelled:false
D/GeniusScanSDK: Selected preview size: 1280x960
    Selected picture size: 1280x960
    Setting flash mode: auto
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.geniusscansdk.simpledemo, PID: 8914
    java.lang.RuntimeException: setParameters failed
        at android.hardware.Camera.native_setParameters(Native Method)
        at android.hardware.Camera.setParameters(Camera.java:2123)
        at com.geniusscansdk.camera.CameraManager.configureCamera(CameraManager.java:368)
        at com.geniusscansdk.camera.CameraManager.access$1300(CameraManager.java:18)
        at com.geniusscansdk.camera.CameraManager$SetupCameraTask.onPostExecute(CameraManager.java:261)
        at com.geniusscansdk.camera.CameraManager$SetupCameraTask.onPostExecute(CameraManager.java:217)
        at android.os.AsyncTask.finish(AsyncTask.java:771)
        at android.os.AsyncTask.access$900(AsyncTask.java:199)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/Process: Sending signal. PID: 8914 SIG: 9
```

**Comment by guillaume-tgl** [comment]
Fixed in v4.0.1: https://geniusscansdk.com/docs/changelog/#401---2021-01-27
