### ISSUE TITLE
[Xamarin] Failed resolution of: Landroidx/camera/core/Preview$SurfaceProvider;

### ISSUE THREAD

**Issue by joshua211** [thegrizzlylabs/geniusscan-sdk-demo#56]
I'm getting an Exception of type `java.lang.NoClassDefFoundError` while trying to call `GeniusScanSDK.Scanflow.PluginBridge.ScanWithConfiguration(Platform.CurrentActivity, configuration);`

Using the latest version of GeniusScanSDK from nuget.

Exception:
`java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/camera/core/Preview$SurfaceProvider;
	at com.geniusscansdk.camera.ScanFragment.createBestForDevice(ScanFragment.java:131)
	at com.geniusscansdk.scanflow.CameraFragment.onCreateView(CameraFragment.java:95)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2995)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:523)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1758)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
	at androidx.fragment.app.FragmentController.execPendingActions(FragmentController.java:462)
	at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:412)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)
	at android.app.Activity.performResume(Activity.java:8129)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4434)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4476)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)`

**Comment by MihaMarkic** [comment]
Same here

**Comment by MihaMarkic** [comment]
@joshua211 
The workaround is to manually install Xamarin.AndroidX.Camera.Lifecycle and Xamarin.AndroidX.Camera.Camera2 NuGet packages.

**Comment by guillaume-tgl** [comment]
Thank for reporting this issue. We're working on a fix for the next version of our SDK. And thanks @MihaMarkic for suggesting this workaround.

**Comment by joshua211** [comment]
@MihaMarkic thanks! I tried many things but for some reason didn't think of that.
