### ISSUE TITLE
Android demo-custom is broken on latest commit

### ISSUE THREAD

**Issue by aelimill** [thegrizzlylabs/geniusscan-sdk-demo#71]
Latest commit (https://github.com/thegrizzlylabs/geniusscan-sdk-demo/commit/527d0baa0fa78dd014966c6e0ff6b3ae0d5c8f2d) broke android demo.

Fatal crash:
```

  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File com.geniusscansdk.demo.model.Page.getOriginalImage()' on a null object reference
        at com.geniusscansdk.demo.processing.BorderDetectionActivity.onResume(BorderDetectionActivity.java:51)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1413)
```

caused by:
```
 java.lang.ClassCastException: com.geniusscansdk.demo.model.Page cannot be cast to android.os.Parcelable
        at android.os.Bundle.getParcelable(Bundle.java:946)
        at android.content.Intent.getParcelableExtra(Intent.java:7485)
        at com.geniusscansdk.demo.processing.BorderDetectionActivity.onCreate(BorderDetectionActivity.java:45)
```

As  `Page` implements `Serializable` now. Changing `BorderDetectionActivity.onCreate` `page = getIntent().getParcelableExtra(EXTRA_PAGE);` to `page = getIntent().getSerializableExtra(EXTRA_PAGE);` doesn't help as also `Quadrangle` doesn't implement `Serializable` so it will crash in BorderDetectionActivity.select method :)

**Comment by guillaume-tgl** [comment]
Thanks for reporting this issue, we're going to fix this in the next version of our SDK.
